// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package arm

import (
	"encoding/json"
	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/kr/pretty"
	"github.com/kylelemons/godebug/diff"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/gen"
	"github.com/leanovate/gopter/prop"
	"os"
	"reflect"
	"testing"
)

func Test_GitHubActionCodeConfiguration_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of GitHubActionCodeConfiguration via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForGitHubActionCodeConfiguration, GitHubActionCodeConfigurationGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForGitHubActionCodeConfiguration runs a test to see if a specific instance of GitHubActionCodeConfiguration round trips to JSON and back losslessly
func RunJSONSerializationTestForGitHubActionCodeConfiguration(subject GitHubActionCodeConfiguration) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual GitHubActionCodeConfiguration
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of GitHubActionCodeConfiguration instances for property testing - lazily instantiated by
// GitHubActionCodeConfigurationGenerator()
var gitHubActionCodeConfigurationGenerator gopter.Gen

// GitHubActionCodeConfigurationGenerator returns a generator of GitHubActionCodeConfiguration instances for property testing.
func GitHubActionCodeConfigurationGenerator() gopter.Gen {
	if gitHubActionCodeConfigurationGenerator != nil {
		return gitHubActionCodeConfigurationGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForGitHubActionCodeConfiguration(generators)
	gitHubActionCodeConfigurationGenerator = gen.Struct(reflect.TypeOf(GitHubActionCodeConfiguration{}), generators)

	return gitHubActionCodeConfigurationGenerator
}

// AddIndependentPropertyGeneratorsForGitHubActionCodeConfiguration is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForGitHubActionCodeConfiguration(gens map[string]gopter.Gen) {
	gens["RuntimeStack"] = gen.PtrOf(gen.AlphaString())
	gens["RuntimeVersion"] = gen.PtrOf(gen.AlphaString())
}

func Test_GitHubActionConfiguration_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of GitHubActionConfiguration via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForGitHubActionConfiguration, GitHubActionConfigurationGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForGitHubActionConfiguration runs a test to see if a specific instance of GitHubActionConfiguration round trips to JSON and back losslessly
func RunJSONSerializationTestForGitHubActionConfiguration(subject GitHubActionConfiguration) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual GitHubActionConfiguration
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of GitHubActionConfiguration instances for property testing - lazily instantiated by
// GitHubActionConfigurationGenerator()
var gitHubActionConfigurationGenerator gopter.Gen

// GitHubActionConfigurationGenerator returns a generator of GitHubActionConfiguration instances for property testing.
// We first initialize gitHubActionConfigurationGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func GitHubActionConfigurationGenerator() gopter.Gen {
	if gitHubActionConfigurationGenerator != nil {
		return gitHubActionConfigurationGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForGitHubActionConfiguration(generators)
	gitHubActionConfigurationGenerator = gen.Struct(reflect.TypeOf(GitHubActionConfiguration{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForGitHubActionConfiguration(generators)
	AddRelatedPropertyGeneratorsForGitHubActionConfiguration(generators)
	gitHubActionConfigurationGenerator = gen.Struct(reflect.TypeOf(GitHubActionConfiguration{}), generators)

	return gitHubActionConfigurationGenerator
}

// AddIndependentPropertyGeneratorsForGitHubActionConfiguration is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForGitHubActionConfiguration(gens map[string]gopter.Gen) {
	gens["GenerateWorkflowFile"] = gen.PtrOf(gen.Bool())
	gens["IsLinux"] = gen.PtrOf(gen.Bool())
}

// AddRelatedPropertyGeneratorsForGitHubActionConfiguration is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForGitHubActionConfiguration(gens map[string]gopter.Gen) {
	gens["CodeConfiguration"] = gen.PtrOf(GitHubActionCodeConfigurationGenerator())
	gens["ContainerConfiguration"] = gen.PtrOf(GitHubActionContainerConfigurationGenerator())
}

func Test_GitHubActionContainerConfiguration_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 100
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of GitHubActionContainerConfiguration via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForGitHubActionContainerConfiguration, GitHubActionContainerConfigurationGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForGitHubActionContainerConfiguration runs a test to see if a specific instance of GitHubActionContainerConfiguration round trips to JSON and back losslessly
func RunJSONSerializationTestForGitHubActionContainerConfiguration(subject GitHubActionContainerConfiguration) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual GitHubActionContainerConfiguration
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of GitHubActionContainerConfiguration instances for property testing - lazily instantiated by
// GitHubActionContainerConfigurationGenerator()
var gitHubActionContainerConfigurationGenerator gopter.Gen

// GitHubActionContainerConfigurationGenerator returns a generator of GitHubActionContainerConfiguration instances for property testing.
func GitHubActionContainerConfigurationGenerator() gopter.Gen {
	if gitHubActionContainerConfigurationGenerator != nil {
		return gitHubActionContainerConfigurationGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForGitHubActionContainerConfiguration(generators)
	gitHubActionContainerConfigurationGenerator = gen.Struct(reflect.TypeOf(GitHubActionContainerConfiguration{}), generators)

	return gitHubActionContainerConfigurationGenerator
}

// AddIndependentPropertyGeneratorsForGitHubActionContainerConfiguration is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForGitHubActionContainerConfiguration(gens map[string]gopter.Gen) {
	gens["ImageName"] = gen.PtrOf(gen.AlphaString())
	gens["Password"] = gen.PtrOf(gen.AlphaString())
	gens["ServerUrl"] = gen.PtrOf(gen.AlphaString())
	gens["Username"] = gen.PtrOf(gen.AlphaString())
}

func Test_SitesSourcecontrolsWeb_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of SitesSourcecontrolsWeb_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForSitesSourcecontrolsWeb_Spec, SitesSourcecontrolsWeb_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForSitesSourcecontrolsWeb_Spec runs a test to see if a specific instance of SitesSourcecontrolsWeb_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForSitesSourcecontrolsWeb_Spec(subject SitesSourcecontrolsWeb_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual SitesSourcecontrolsWeb_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of SitesSourcecontrolsWeb_Spec instances for property testing - lazily instantiated by
// SitesSourcecontrolsWeb_SpecGenerator()
var sitesSourcecontrolsWeb_SpecGenerator gopter.Gen

// SitesSourcecontrolsWeb_SpecGenerator returns a generator of SitesSourcecontrolsWeb_Spec instances for property testing.
// We first initialize sitesSourcecontrolsWeb_SpecGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func SitesSourcecontrolsWeb_SpecGenerator() gopter.Gen {
	if sitesSourcecontrolsWeb_SpecGenerator != nil {
		return sitesSourcecontrolsWeb_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForSitesSourcecontrolsWeb_Spec(generators)
	sitesSourcecontrolsWeb_SpecGenerator = gen.Struct(reflect.TypeOf(SitesSourcecontrolsWeb_Spec{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForSitesSourcecontrolsWeb_Spec(generators)
	AddRelatedPropertyGeneratorsForSitesSourcecontrolsWeb_Spec(generators)
	sitesSourcecontrolsWeb_SpecGenerator = gen.Struct(reflect.TypeOf(SitesSourcecontrolsWeb_Spec{}), generators)

	return sitesSourcecontrolsWeb_SpecGenerator
}

// AddIndependentPropertyGeneratorsForSitesSourcecontrolsWeb_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForSitesSourcecontrolsWeb_Spec(gens map[string]gopter.Gen) {
	gens["Kind"] = gen.PtrOf(gen.AlphaString())
	gens["Name"] = gen.AlphaString()
}

// AddRelatedPropertyGeneratorsForSitesSourcecontrolsWeb_Spec is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForSitesSourcecontrolsWeb_Spec(gens map[string]gopter.Gen) {
	gens["Properties"] = gen.PtrOf(Sites_Sourcecontrols_Web_Properties_SpecGenerator())
}

func Test_Sites_Sourcecontrols_Web_Properties_Spec_WhenSerializedToJson_DeserializesAsEqual(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 80
	parameters.MaxSize = 3
	properties := gopter.NewProperties(parameters)
	properties.Property(
		"Round trip of Sites_Sourcecontrols_Web_Properties_Spec via JSON returns original",
		prop.ForAll(RunJSONSerializationTestForSites_Sourcecontrols_Web_Properties_Spec, Sites_Sourcecontrols_Web_Properties_SpecGenerator()))
	properties.TestingRun(t, gopter.NewFormatedReporter(true, 240, os.Stdout))
}

// RunJSONSerializationTestForSites_Sourcecontrols_Web_Properties_Spec runs a test to see if a specific instance of Sites_Sourcecontrols_Web_Properties_Spec round trips to JSON and back losslessly
func RunJSONSerializationTestForSites_Sourcecontrols_Web_Properties_Spec(subject Sites_Sourcecontrols_Web_Properties_Spec) string {
	// Serialize to JSON
	bin, err := json.Marshal(subject)
	if err != nil {
		return err.Error()
	}

	// Deserialize back into memory
	var actual Sites_Sourcecontrols_Web_Properties_Spec
	err = json.Unmarshal(bin, &actual)
	if err != nil {
		return err.Error()
	}

	// Check for outcome
	match := cmp.Equal(subject, actual, cmpopts.EquateEmpty())
	if !match {
		actualFmt := pretty.Sprint(actual)
		subjectFmt := pretty.Sprint(subject)
		result := diff.Diff(subjectFmt, actualFmt)
		return result
	}

	return ""
}

// Generator of Sites_Sourcecontrols_Web_Properties_Spec instances for property testing - lazily instantiated by
// Sites_Sourcecontrols_Web_Properties_SpecGenerator()
var sites_Sourcecontrols_Web_Properties_SpecGenerator gopter.Gen

// Sites_Sourcecontrols_Web_Properties_SpecGenerator returns a generator of Sites_Sourcecontrols_Web_Properties_Spec instances for property testing.
// We first initialize sites_Sourcecontrols_Web_Properties_SpecGenerator with a simplified generator based on the
// fields with primitive types then replacing it with a more complex one that also handles complex fields
// to ensure any cycles in the object graph properly terminate.
func Sites_Sourcecontrols_Web_Properties_SpecGenerator() gopter.Gen {
	if sites_Sourcecontrols_Web_Properties_SpecGenerator != nil {
		return sites_Sourcecontrols_Web_Properties_SpecGenerator
	}

	generators := make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForSites_Sourcecontrols_Web_Properties_Spec(generators)
	sites_Sourcecontrols_Web_Properties_SpecGenerator = gen.Struct(reflect.TypeOf(Sites_Sourcecontrols_Web_Properties_Spec{}), generators)

	// The above call to gen.Struct() captures the map, so create a new one
	generators = make(map[string]gopter.Gen)
	AddIndependentPropertyGeneratorsForSites_Sourcecontrols_Web_Properties_Spec(generators)
	AddRelatedPropertyGeneratorsForSites_Sourcecontrols_Web_Properties_Spec(generators)
	sites_Sourcecontrols_Web_Properties_SpecGenerator = gen.Struct(reflect.TypeOf(Sites_Sourcecontrols_Web_Properties_Spec{}), generators)

	return sites_Sourcecontrols_Web_Properties_SpecGenerator
}

// AddIndependentPropertyGeneratorsForSites_Sourcecontrols_Web_Properties_Spec is a factory method for creating gopter generators
func AddIndependentPropertyGeneratorsForSites_Sourcecontrols_Web_Properties_Spec(gens map[string]gopter.Gen) {
	gens["Branch"] = gen.PtrOf(gen.AlphaString())
	gens["DeploymentRollbackEnabled"] = gen.PtrOf(gen.Bool())
	gens["IsGitHubAction"] = gen.PtrOf(gen.Bool())
	gens["IsManualIntegration"] = gen.PtrOf(gen.Bool())
	gens["IsMercurial"] = gen.PtrOf(gen.Bool())
	gens["RepoUrl"] = gen.PtrOf(gen.AlphaString())
}

// AddRelatedPropertyGeneratorsForSites_Sourcecontrols_Web_Properties_Spec is a factory method for creating gopter generators
func AddRelatedPropertyGeneratorsForSites_Sourcecontrols_Web_Properties_Spec(gens map[string]gopter.Gen) {
	gens["GitHubActionConfiguration"] = gen.PtrOf(GitHubActionConfigurationGenerator())
}
