// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package customizations

import (
	v20220301 "github.com/Azure/azure-service-operator/v2/api/web/v1api20220301"
	storage "github.com/Azure/azure-service-operator/v2/api/web/v1api20220301/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
)

type SitesSourcecontrolsWebExtension struct {
}

// GetExtendedResources Returns the KubernetesResource slice for Resource versions
func (extension *SitesSourcecontrolsWebExtension) GetExtendedResources() []genruntime.KubernetesResource {
	return []genruntime.KubernetesResource{
		&v20220301.SitesSourcecontrolsWeb{},
		&storage.SitesSourcecontrolsWeb{}}
}
