// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package storage

import (
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/conditions"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/configmaps"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/core"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/secrets"
	"github.com/rotisserie/eris"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// +kubebuilder:rbac:groups=web.azure.com,resources=sitessourcecontrolswebs,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=web.azure.com,resources={sitessourcecontrolswebs/status,sitessourcecontrolswebs/finalizers},verbs=get;update;patch

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Severity",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].severity"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Message",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].message"
// Storage version of v1api20220301.SitesSourcecontrolsWeb
// Generator information:
// - Generated from: /web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/sourcecontrols/web
type SitesSourcecontrolsWeb struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SitesSourcecontrolsWeb_Spec   `json:"spec,omitempty"`
	Status            SitesSourcecontrolsWeb_STATUS `json:"status,omitempty"`
}

var _ conditions.Conditioner = &SitesSourcecontrolsWeb{}

// GetConditions returns the conditions of the resource
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) GetConditions() conditions.Conditions {
	return sourcecontrolsWeb.Status.Conditions
}

// SetConditions sets the conditions on the resource status
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) SetConditions(conditions conditions.Conditions) {
	sourcecontrolsWeb.Status.Conditions = conditions
}

var _ configmaps.Exporter = &SitesSourcecontrolsWeb{}

// ConfigMapDestinationExpressions returns the Spec.OperatorSpec.ConfigMapExpressions property
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) ConfigMapDestinationExpressions() []*core.DestinationExpression {
	if sourcecontrolsWeb.Spec.OperatorSpec == nil {
		return nil
	}
	return sourcecontrolsWeb.Spec.OperatorSpec.ConfigMapExpressions
}

var _ secrets.Exporter = &SitesSourcecontrolsWeb{}

// SecretDestinationExpressions returns the Spec.OperatorSpec.SecretExpressions property
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) SecretDestinationExpressions() []*core.DestinationExpression {
	if sourcecontrolsWeb.Spec.OperatorSpec == nil {
		return nil
	}
	return sourcecontrolsWeb.Spec.OperatorSpec.SecretExpressions
}

var _ genruntime.KubernetesResource = &SitesSourcecontrolsWeb{}

// AzureName returns the Azure name of the resource (always "web")
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) AzureName() string {
	return "web"
}

// GetAPIVersion returns the ARM API version of the resource. This is always "2022-03-01"
func (sourcecontrolsWeb SitesSourcecontrolsWeb) GetAPIVersion() string {
	return "2022-03-01"
}

// GetResourceScope returns the scope of the resource
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) GetResourceScope() genruntime.ResourceScope {
	return genruntime.ResourceScopeResourceGroup
}

// GetSpec returns the specification of this resource
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) GetSpec() genruntime.ConvertibleSpec {
	return &sourcecontrolsWeb.Spec
}

// GetStatus returns the status of this resource
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) GetStatus() genruntime.ConvertibleStatus {
	return &sourcecontrolsWeb.Status
}

// GetSupportedOperations returns the operations supported by the resource
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) GetSupportedOperations() []genruntime.ResourceOperation {
	return []genruntime.ResourceOperation{
		genruntime.ResourceOperationDelete,
		genruntime.ResourceOperationGet,
		genruntime.ResourceOperationPut,
	}
}

// GetType returns the ARM Type of the resource. This is always "Microsoft.Web/sites/sourcecontrols/web"
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) GetType() string {
	return "Microsoft.Web/sites/sourcecontrols/web"
}

// NewEmptyStatus returns a new empty (blank) status
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) NewEmptyStatus() genruntime.ConvertibleStatus {
	return &SitesSourcecontrolsWeb_STATUS{}
}

// Owner returns the ResourceReference of the owner
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) Owner() *genruntime.ResourceReference {
	if sourcecontrolsWeb.Spec.Owner == nil {
		return nil
	}

	group, kind := genruntime.LookupOwnerGroupKind(sourcecontrolsWeb.Spec)
	return sourcecontrolsWeb.Spec.Owner.AsResourceReference(group, kind)
}

// SetStatus sets the status of this resource
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) SetStatus(status genruntime.ConvertibleStatus) error {
	// If we have exactly the right type of status, assign it
	if st, ok := status.(*SitesSourcecontrolsWeb_STATUS); ok {
		sourcecontrolsWeb.Status = *st
		return nil
	}

	// Convert status to required version
	var st SitesSourcecontrolsWeb_STATUS
	err := status.ConvertStatusTo(&st)
	if err != nil {
		return eris.Wrap(err, "failed to convert status")
	}

	sourcecontrolsWeb.Status = st
	return nil
}

// Hub marks that this SitesSourcecontrolsWeb is the hub type for conversion
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) Hub() {}

// OriginalGVK returns a GroupValueKind for the original API version used to create the resource
func (sourcecontrolsWeb *SitesSourcecontrolsWeb) OriginalGVK() *schema.GroupVersionKind {
	return &schema.GroupVersionKind{
		Group:   GroupVersion.Group,
		Version: sourcecontrolsWeb.Spec.OriginalVersion,
		Kind:    "SitesSourcecontrolsWeb",
	}
}

// +kubebuilder:object:root=true
// Storage version of v1api20220301.SitesSourcecontrolsWeb
// Generator information:
// - Generated from: /web/resource-manager/Microsoft.Web/stable/2022-03-01/WebApps.json
// - ARM URI: /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/sourcecontrols/web
type SitesSourcecontrolsWebList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SitesSourcecontrolsWeb `json:"items"`
}

// Storage version of v1api20220301.SitesSourcecontrolsWeb_Spec
type SitesSourcecontrolsWeb_Spec struct {
	Branch                    *string                             `json:"branch,omitempty"`
	DeploymentRollbackEnabled *bool                               `json:"deploymentRollbackEnabled,omitempty"`
	GitHubActionConfiguration *GitHubActionConfiguration          `json:"gitHubActionConfiguration,omitempty"`
	IsGitHubAction            *bool                               `json:"isGitHubAction,omitempty"`
	IsManualIntegration       *bool                               `json:"isManualIntegration,omitempty"`
	IsMercurial               *bool                               `json:"isMercurial,omitempty"`
	Kind                      *string                             `json:"kind,omitempty"`
	OperatorSpec              *SitesSourcecontrolsWebOperatorSpec `json:"operatorSpec,omitempty"`
	OriginalVersion           string                              `json:"originalVersion,omitempty"`

	// +kubebuilder:validation:Required
	// Owner: The owner of the resource. The owner controls where the resource goes when it is deployed. The owner also
	// controls the resources lifecycle. When the owner is deleted the resource will also be deleted. Owner is expected to be a
	// reference to a web.azure.com/Site resource
	Owner       *genruntime.KnownResourceReference `group:"web.azure.com" json:"owner,omitempty" kind:"Site"`
	PropertyBag genruntime.PropertyBag             `json:"$propertyBag,omitempty"`
	RepoUrl     *string                            `json:"repoUrl,omitempty"`
}

var _ genruntime.ConvertibleSpec = &SitesSourcecontrolsWeb_Spec{}

// ConvertSpecFrom populates our SitesSourcecontrolsWeb_Spec from the provided source
func (sourcecontrolsWeb *SitesSourcecontrolsWeb_Spec) ConvertSpecFrom(source genruntime.ConvertibleSpec) error {
	if source == sourcecontrolsWeb {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return source.ConvertSpecTo(sourcecontrolsWeb)
}

// ConvertSpecTo populates the provided destination from our SitesSourcecontrolsWeb_Spec
func (sourcecontrolsWeb *SitesSourcecontrolsWeb_Spec) ConvertSpecTo(destination genruntime.ConvertibleSpec) error {
	if destination == sourcecontrolsWeb {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleSpec")
	}

	return destination.ConvertSpecFrom(sourcecontrolsWeb)
}

// Storage version of v1api20220301.SitesSourcecontrolsWeb_STATUS
type SitesSourcecontrolsWeb_STATUS struct {
	Branch                    *string                           `json:"branch,omitempty"`
	Conditions                []conditions.Condition            `json:"conditions,omitempty"`
	DeploymentRollbackEnabled *bool                             `json:"deploymentRollbackEnabled,omitempty"`
	GitHubActionConfiguration *GitHubActionConfiguration_STATUS `json:"gitHubActionConfiguration,omitempty"`
	Id                        *string                           `json:"id,omitempty"`
	IsGitHubAction            *bool                             `json:"isGitHubAction,omitempty"`
	IsManualIntegration       *bool                             `json:"isManualIntegration,omitempty"`
	IsMercurial               *bool                             `json:"isMercurial,omitempty"`
	Kind                      *string                           `json:"kind,omitempty"`
	Name                      *string                           `json:"name,omitempty"`
	PropertyBag               genruntime.PropertyBag            `json:"$propertyBag,omitempty"`
	RepoUrl                   *string                           `json:"repoUrl,omitempty"`
	Type                      *string                           `json:"type,omitempty"`
}

var _ genruntime.ConvertibleStatus = &SitesSourcecontrolsWeb_STATUS{}

// ConvertStatusFrom populates our SitesSourcecontrolsWeb_STATUS from the provided source
func (sourcecontrolsWeb *SitesSourcecontrolsWeb_STATUS) ConvertStatusFrom(source genruntime.ConvertibleStatus) error {
	if source == sourcecontrolsWeb {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return source.ConvertStatusTo(sourcecontrolsWeb)
}

// ConvertStatusTo populates the provided destination from our SitesSourcecontrolsWeb_STATUS
func (sourcecontrolsWeb *SitesSourcecontrolsWeb_STATUS) ConvertStatusTo(destination genruntime.ConvertibleStatus) error {
	if destination == sourcecontrolsWeb {
		return eris.New("attempted conversion between unrelated implementations of github.com/Azure/azure-service-operator/v2/pkg/genruntime/ConvertibleStatus")
	}

	return destination.ConvertStatusFrom(sourcecontrolsWeb)
}

// Storage version of v1api20220301.GitHubActionConfiguration
// The GitHub action configuration.
type GitHubActionConfiguration struct {
	CodeConfiguration      *GitHubActionCodeConfiguration      `json:"codeConfiguration,omitempty"`
	ContainerConfiguration *GitHubActionContainerConfiguration `json:"containerConfiguration,omitempty"`
	GenerateWorkflowFile   *bool                               `json:"generateWorkflowFile,omitempty"`
	IsLinux                *bool                               `json:"isLinux,omitempty"`
	PropertyBag            genruntime.PropertyBag              `json:"$propertyBag,omitempty"`
}

// Storage version of v1api20220301.GitHubActionConfiguration_STATUS
// The GitHub action configuration.
type GitHubActionConfiguration_STATUS struct {
	CodeConfiguration      *GitHubActionCodeConfiguration_STATUS      `json:"codeConfiguration,omitempty"`
	ContainerConfiguration *GitHubActionContainerConfiguration_STATUS `json:"containerConfiguration,omitempty"`
	GenerateWorkflowFile   *bool                                      `json:"generateWorkflowFile,omitempty"`
	IsLinux                *bool                                      `json:"isLinux,omitempty"`
	PropertyBag            genruntime.PropertyBag                     `json:"$propertyBag,omitempty"`
}

// Storage version of v1api20220301.SitesSourcecontrolsWebOperatorSpec
// Details for configuring operator behavior. Fields in this struct are interpreted by the operator directly rather than being passed to Azure
type SitesSourcecontrolsWebOperatorSpec struct {
	ConfigMapExpressions []*core.DestinationExpression `json:"configMapExpressions,omitempty"`
	PropertyBag          genruntime.PropertyBag        `json:"$propertyBag,omitempty"`
	SecretExpressions    []*core.DestinationExpression `json:"secretExpressions,omitempty"`
}

// Storage version of v1api20220301.GitHubActionCodeConfiguration
// The GitHub action code configuration.
type GitHubActionCodeConfiguration struct {
	PropertyBag    genruntime.PropertyBag `json:"$propertyBag,omitempty"`
	RuntimeStack   *string                `json:"runtimeStack,omitempty"`
	RuntimeVersion *string                `json:"runtimeVersion,omitempty"`
}

// Storage version of v1api20220301.GitHubActionCodeConfiguration_STATUS
// The GitHub action code configuration.
type GitHubActionCodeConfiguration_STATUS struct {
	PropertyBag    genruntime.PropertyBag `json:"$propertyBag,omitempty"`
	RuntimeStack   *string                `json:"runtimeStack,omitempty"`
	RuntimeVersion *string                `json:"runtimeVersion,omitempty"`
}

// Storage version of v1api20220301.GitHubActionContainerConfiguration
// The GitHub action container configuration.
type GitHubActionContainerConfiguration struct {
	ImageName   *string                     `json:"imageName,omitempty"`
	Password    *genruntime.SecretReference `json:"password,omitempty"`
	PropertyBag genruntime.PropertyBag      `json:"$propertyBag,omitempty"`
	ServerUrl   *string                     `json:"serverUrl,omitempty"`
	Username    *string                     `json:"username,omitempty"`
}

// Storage version of v1api20220301.GitHubActionContainerConfiguration_STATUS
// The GitHub action container configuration.
type GitHubActionContainerConfiguration_STATUS struct {
	ImageName   *string                `json:"imageName,omitempty"`
	PropertyBag genruntime.PropertyBag `json:"$propertyBag,omitempty"`
	ServerUrl   *string                `json:"serverUrl,omitempty"`
	Username    *string                `json:"username,omitempty"`
}

func init() {
	SchemeBuilder.Register(&SitesSourcecontrolsWeb{}, &SitesSourcecontrolsWebList{})
}
